### ISSUE TITLE
Missing icons in 5.6.1

### ISSUE THREAD

**Issue by JM-Mendez** [moxer-theme/moxer-icons-code#21]
**Describe the bug**
Version 5.6.1 auto updated and the icons are missing. Downgrading to 5.6.0 works well

Love your icons btw 😃

**Comment by ctf0** [comment]
same here

**Comment by cristiands7** [comment]
I have the same issue.

**Comment by Tomv-m** [comment]
Have also the same issue. In the config the `"iconDefinitions"` is empty.

**Comment by thiagolucio** [comment]
Same here:
 OS: Fedora x86_64 
 Model: Latitude 3400 
  Kernel: 5.10.15-200.fc33.x86_64 
     Shell: /bin/bash 5.0.17 
       CPU: Intel i5-8265U (8) @ 3.900GHz [49.0°on] 
       CPU Usage: 20% 
                 Memory: 5974MiB / 15872MiB 
                 GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
                 Resolution: 2560x1080 
![Screenshot from 2021-02-21 11-50-48](https://user-images.githubusercontent.com/5756266/108628682-0fafbd00-743b-11eb-9f07-c0ccbb5673d0.png)

**Comment by cristiands7** [comment]
> Have also the same issue. In the config the `"iconDefinitions"` is empty.

`"iconDefinitions"` config depends on icons download is finished. When that config is generated files has not been finish downloaded yet.

**Comment by equinusocio** [comment]
Hello, can you check with the latest version?

**Comment by JM-Mendez** [comment]
It works, thank you 😃
