### ISSUE TITLE
Add Nim & Nimble Icons

### ISSUE THREAD

**Issue by g33kidd** [moxer-theme/moxer-icons-code#22]

**Comment by equinusocio** [comment]
Hello, can you provide more info about this request? We need to know:
- Language ID
- File extensions
- Where to find the official svg icon

**Comment by gusbemacbe** [comment]
> * Language ID

nim and nimble

> * File extensions

nim

> * Where to find the official svg icon

https://github.com/nim-lang/assets/tree/master/Art

**Comment by equinusocio** [comment]
Released
