### ISSUE TITLE
Out of VSCode Marketplace 

### ISSUE THREAD

**Issue by thiagolucio** [moxer-theme/moxer-icons-code#23]
Hi Guys. 
I don't know if you stop dev this extension (it's great in my opinion) but it not anymore in VSCode Marketplace. I think you need to get a review of this case if you like. 
![out](https://user-images.githubusercontent.com/5756266/111032818-e4424180-83ec-11eb-967d-1da610706b5c.png)

**Comment by thiagolucio** [comment]
![errorMsg](https://user-images.githubusercontent.com/5756266/111033207-ca096300-83ee-11eb-9c69-4cb552003fc5.png)

**Comment by equinusocio** [comment]
Hello, we had a problem with the vsce CLI and we accidentally deleted our pubisher account. Here more info
https://github.com/moxer-theme/moxer-icons-code/issues/24
