### ISSUE TITLE
Manual Installation doesn't work...Can't stop the Update force version.

### ISSUE THREAD

**Issue by thiagolucio** [moxer-theme/moxer-icons-code#25]
The manual installation process is useless because the first time the VSCode is started, the extension is updated in a mandatory way and it is not possible to work with the previous version and the extension does not work again.

Even changing permissions for extension 5.6.2 and 5.6.3 is installed and replaced, becoming the one used. Again we have the problem.
![Screenshot from 2021-03-17 10-56-47](https://user-images.githubusercontent.com/5756266/111479733-018a4f00-8710-11eb-9b47-622349ea9019.png)
![Screenshot from 2021-03-17 10-59-23](https://user-images.githubusercontent.com/5756266/111479743-05b66c80-8710-11eb-942e-b4c10c386205.png)

     /   __)\    ================== 
     |  /  \ \   OS: Fedora x86_64 
  ___|  |__/ /   Model: Latitude 3400 
 / (_    _)_/    Kernel: 5.10.22-200.fc33.x86_64 
/ /  |  |        Shell: /bin/bash 5.0.17 
\ \__/  |        CPU: Intel i5-8265U (8) @ 3.900GHz [53.0°on] 
 \(_____/        CPU Usage: 26% 
                 Memory: 4518MiB / 15872MiB 
                 GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
                 Resolution: 2560x1080

**Comment by thiagolucio** [comment]
> The manual installation process is useless because the first time the VSCode is started, the extension is updated in a mandatory way and it is not possible to work with the previous version and the extension does not work again.
> 
> Even changing permissions for extension 5.6.2 and 5.6.3 is installed and replaced, becoming the one used. Again we have the problem.
> ![Screenshot from 2021-03-17 10-56-47](https://user-images.githubusercontent.com/5756266/111479733-018a4f00-8710-11eb-9b47-622349ea9019.png)
> ![Screenshot from 2021-03-17 10-59-23](https://user-images.githubusercontent.com/5756266/111479743-05b66c80-8710-11eb-942e-b4c10c386205.png)
> 
> ```
>  /   __)\    ================== 
>  |  /  \ \   OS: Fedora x86_64 
> ```
> 
> _**| |**/ / Model: Latitude 3400 / (_ _)_/ Kernel: 5.10.22-200.fc33.x86_64
> / / | | Shell: /bin/bash 5.0.17
> \ __/ | CPU: Intel i5-8265U (8) @ 3.900GHz [53.0°on]
> (_____/ CPU Usage: 26%
> Memory: 4518MiB / 15872MiB
> GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620]
> Resolution: 2560x1080

If It's possible to make a suggestion. Why you just put the before version 5.6.2 in vscode official store. I think this solves the problem. When the new version be stable you make the change.

**Comment by equinusocio** [comment]
Hello, what's exactly is the problem here? If you install an older version (manually or not) the marketplace will update it with the new one since both extensions are the same. The auto-update can be disabled via vscode settings:

https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate

**Comment by thiagolucio** [comment]
> Hello, what's exactly is the problem here? If you install an older version (manually or not) vscode will update it from the marketplace with the new one since both extensions are the same thing. The auto-update can be disabled via vscode settings:
> 
> https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate
> 
> About the 5.6.3 bug we're working on it and we'll release it soon.

**Comment by thiagolucio** [comment]
> Hello, what's exactly is the problem here? If you install an older version (manually or not) vscode will update it from the marketplace with the new one since both extensions are the same thing. The auto-update can be disabled via vscode settings:
> 
> https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate
> 
> About the 5.6.3 bug we're working on it and we'll release it soon.

The problem is that the versions are not spoken. I believe that since the installation of the previous version is done manually, the update is automated and it is not possible to prevent it from happening. When the extension is updated, it stops working and is no longer visible in the editor. All icons disappear and no longer appear.

I am informing you with the intention of helping. Assuming you are interested in maintaining the extent that you have had so much work to do. If you are bothering, just let me know that I simply stop informing and start using another extension. There are several, only this is my favorite. That's why I take the trouble to contribute.

**Comment by equinusocio** [comment]
I'm sorry of that, but the issue title and description are all but clear about the issue (auto update or broken extension?) itself. We appreciate you like the extension, but we need clear issues to understand what's going on and work on fixes.

Anyway, we released `5.7.2` which fixes the missing icons.
