### ISSUE TITLE
Folder Icons

### ISSUE THREAD

**Issue by DominicVonk** [moxer-theme/moxer-icons-code#26]
I would like also the folder icons like material icon theme.

**Comment by equinusocio** [comment]
Hello, what do you mean?  Moxer Icons already provides icons for folders

**Comment by DominicVonk** [comment]
I mean more folder icons like the test folder icon

**Comment by equinusocio** [comment]
Can you share a list of folder names for which you want the icon?

**Comment by DominicVonk** [comment]
Hi, thank you, this is a list maybe I've missed some. But I think this will cover most

- Library / lib
- Services
- Repositories
- Resources
- API
- Src
- Dist
- Js
- Css
- Assets
- Images / img
- Models
- Components
- Modules
- Helpers
- Templates
- Utilities / utils
- Public
- Private
- Storage
- Logs / log
- Routes
- Database
- Config
- Bootstrap
- Rules
- Providers
- Policies
- Notifications
- Mail
- Listeners
- Jobs / Queues
- Events
- Exceptions
- Bin
- Examples / Samples
- Packages
- Build
- Docs
- Artifacts

**Comment by equinusocio** [comment]
Hello, i'm closing this issue since my time and focus is currently on material theme and this task is not planned.

**Comment by equinusocio** [comment]
Hello, i'm closing this issue since my time and focus is currently on material theme and this task is not planned.
