### ISSUE TITLE
Allow us to custom icons for specific folders and icons you do not want to add to your project

### ISSUE THREAD

**Issue by gusbemacbe** [moxer-theme/moxer-icons-code#27]
**Is your feature request related to a problem? Please describe.**
It is a pain that your project is different from @Pkief's Material Icon Theme, which allows me to custom icons for specific folders and icons. 

**Describe the solution you'd like**
For example, of course you will not want to add more than 6k country flag and regional language flag icons to your project, then allow us to custom the icons for folders and icons. 

**Describe alternatives you've considered**
Get inspired by Pkief's Material Icon theme example; https://github.com/PKief/vscode-material-icon-theme#custom-svg-icons

**Additional context**

- Moxer:
   ![image](https://user-images.githubusercontent.com/2257024/113495469-6c85a500-94c8-11eb-9c19-393aa2e85345.png)

- Material
   ![image](https://user-images.githubusercontent.com/2257024/113495537-f170be80-94c8-11eb-9b3a-de5e1bf67171.png)

**Comment by equinusocio** [comment]
Hello, at the moment this feature is not on the roadmap. I want to keep this theme simple and fast.
