### ISSUE TITLE
Ability to override icon selection

### ISSUE THREAD

**Issue by vanekj** [moxer-theme/moxer-icons-code#32]
Hello,

I would like to ask for a **feature** which would allow me to change icon selection for specific file/folder.

Currently, I am working on a project using NestJS framework, which is using files `.module.ts`, `.service.ts`, etc. and it's icon is set to Angular, which I don't like and would like to switch it to normal TS extension by specifying it in settings.

Thank you 🙏🏻

**Comment by equinusocio** [comment]
Unfortunately there is no way to allow icons customizations, but we just removed all the angular-specific icons. Now such files will just show the languageId/extension icon (ts)
