### ISSUE TITLE
Add Elixir icons

### ISSUE THREAD

**Issue by lesha1201** [moxer-theme/moxer-icons-code#4]
First of all I want to say thank you for worked you've done.

I find that files with extensions: `.ex`, `.exs` don't have icons. Can you please add icons for Elixir?

P.S. Elixir lock file have an icon (https://github.com/moxer-theme/moxer-icons/blob/master/svgs/elixir-lock.svg)

**Comment by equinusocio** [comment]
Added in `5.1.0`
