### ISSUE TITLE
Support Explorer file nesting

### ISSUE THREAD

**Issue by selrond** [moxer-theme/moxer-icons-code#40]
It would be great to display folder-like indicators of nested files.

Context: [Explorer file nesting](https://code.visualstudio.com/updates/v1_64#_explorer-file-nesting "Explorer file nesting")

**Comment by equinusocio** [comment]
Hi @selrond, the new experimental settings must be defined in user preferences, not forced by themes. You are free to add those settings directly in your preference json

**Comment by selrond** [comment]
@equinusocio I’m aware of that, but certain icon packs (like this one) don’t seem to be aware of the nesting and don’t display unfold indicator next to those files. Consider:

`Seti (Visual Studio Code)`:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/6603389/157217370-c6bb83dd-b4ee-42fb-bd81-03e3b38291eb.png">

Moxer icons:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/6603389/157217431-d6dd4b9e-f456-49b5-b080-046efba95191.png">

When using Moxer, there’s no way to see that the file "contains" nested files

**Comment by equinusocio** [comment]
This behavior is handled by VSC. Moxer icons hide the arrow/caret indicator and use the folder icon for folders. We don't have any control of what to show besides files. VSC put only the caret beside the "nested" files, that is hidden by the theme, this means that enabling theme again the caret will appear beside each folder too.

To try this, you can set `hidesExplorerArrows: false` inside your local theme file at:
`~/.vscode/extensions/equinusocio.moxer-icons-5.8.0/build/moxer-icons.json`

**Comment by selrond** [comment]
I see, thanks for an insight!
This is a bit unfortunate though

**Comment by equinusocio** [comment]
I would suggest reporting this feature request to the VSC team, they should provide/use an additional indicator to customize for "nested" files, like the folder icons used for folders.

**Comment by selrond** [comment]
Good news:
https://github.com/microsoft/vscode/issues/6328#issuecomment-1062025331

**Comment by equinusocio** [comment]
Reopening until we have the API to fix this.

**Comment by equinusocio** [comment]
[This issue](https://github.com/microsoft/vscode/issues/6328#issuecomment-1062025331) is now closed but i don't see way to handle it via themes API.
